FROM lukemathwalker/cargo-chef:latest-rust-1 AS chef

WORKDIR /app

FROM chef AS planner

COPY . .

RUN cargo chef prepare --bin llm-gateway-client --recipe-path recipe.json

FROM chef AS builder

ARG PROFILE=release

COPY --from=planner /app/recipe.json recipe.json

# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json

# Build application
COPY . .

RUN cargo build --profile ${PROFILE} --bin llm-gateway-client

# We do not need the Rust toolchain to run the binary!
FROM debian:bookworm-slim AS runtime

ARG PROFILE=release

RUN apt-get update && apt install -y openssl

WORKDIR /app

COPY --from=builder /app/target/${PROFILE}/llm-gateway-client /usr/local/bin

ENTRYPOINT ["/usr/local/bin/llm-gateway-client"]
